### ISSUE TITLE
Google short links appear to have an issue

### ISSUE THREAD

**Issue by jarradstevenson** [pawel-ochrymowicz/google-maps-to-waze#3]
https://maps.app.goo.gl/twEJoiCXaSkfN95E9 I used this link as a test.  Apart from that an excellent little app.  My workaround, copy and paste into the browser, copy long link from the browser and send to your Bot

**Comment by pawel-ochrymowicz** [comment]
> https://maps.app.goo.gl/twEJoiCXaSkfN95E9 I used this link as a test. Apart from that an excellent little app. My workaround, copy and paste into the browser, copy long link from the browser and send to your Bot

Thanks. I will take a look.

**Comment by pawel-ochrymowicz** [comment]
I fixed your case but I can not guarantee it will work in every situation due to:
* Unpredictability of the short links
* My very limited amount of free time

Feel free to contribute and/or test.
Thanks again for the feedback.
